<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [232]:
#Creating function to Multiply any two matrices

A   = [[1, 2],
      [3, 4]]
B   = [[1, 2, 3, 4, 5],
      [5 ,6 ,7, 8 ,9]]








m= len(A)
n=len(B[0])



def Multiply(A,B):
  if len(A[0]) == len(B) :     #checking if our matices are satisfying condition for dot product
    mul_mat = [ [ 0 for i in range(n) ] for j in range(m) ]   #Creating  empty matrix of the size of our row of matrix A and column of matrix B usin list comprehension 
    
    for i in range(len(A)):      #to select row  from matrix A
        
      for j in range(len(B[0])):   #to select  columns from matrix B
            
        for k in range(len(B)):       #to select rows from matrix A        
          mul_mat[i][j] += A[i][k] * B[k][j]      #Multiplying components from both matrices A And B and adding in to variable mul_mat
    return mul_mat
    
  else:
    print(' Given two matrices multiplication is not possible') #printing clause that our matrices can not be multiply




print("Result: ")
Multiply(A,B)
    
    


Result: 


[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [234]:
import random


A = [0,5,27,6,13,28,100,45,10,79]


def pick_a_number_from_list(A):            
    sum=0
    cummulative=[]                            #cummmulative sum list
    for i in range(len(A)):
        sum = sum + A[i]                   #creating cummulative sum
        cummulative.append(sum)            #adding sum into cum_sum
    
     
    R = int(random.uniform(0,sum))    #generating randoms  from 0 to sum
    

    for index in range(len(cummulative)):            #creating index for the cum_sum

      if(R>=cummulative[index] and R<cummulative[index+1]):   #  checking for range r>=cum_sum[index] and r<cum_sum[index+1]

        return A[index+1]                              # using the number A[index+1]
    
   

def sampling_based_on_magnitued():
    
    num = dict()                                        #creating dict 

    for i in range(1,100):                             #sampling based on magnitude
        number = pick_a_number_from_list(A)            #picking number from list A
        if number not in num:                          
            num[number] = 1
        else:
            num[number]+=1                            #adding 1 each time given number from A appears                        
    print(num)

sampling_based_on_magnitued()


{27: 9, 45: 13, 100: 41, 28: 9, 6: 3, 79: 16, 13: 6, 10: 2}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [235]:
import re
A = "#2a$#b%c%561# "
k='#' 

def Digi_string(A): 
  
  A = filter(str.isdigit, A)        #filtering out digit from string
  A= "".join(A)                     #assign digit to A
  if A.isdigit():                   #if it is digit replace with K=# other wise print 'empty string'
    res = re.sub(r'\d',k, A)
    print(res)
  else:
    print('(empty string)')
  
    

Digi_string(A) 

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [236]:
import math
from typing import ValuesView
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
Report_card = list(zip(Students, Marks))     #converting both list into one

# sort the list of tuples on the Report_card, so selecting the second element (index 1) of the tuple  
Report_card.sort(key = lambda e: e[1])
#print(Report_card)

def display_dash_board(Report_card):
   top_5 = Report_card[5:]                  #Slicing top5 rank  student in increasing order

   top_5_students=top_5[::-1]          #reversing top 5 rank student in descending order 
   print('a:',top_5_students)
   

   least_5_students=Report_card[:5]
   print('b:',least_5_students)       #least_5_student in increasing order



   twenty_5th = math.floor(len(Report_card) // 4)
   seventy_5th = math.floor(3 * len(Report_card) // 4)
  
   between = Report_card[twenty_5th:seventy_5th]
   print('c:',between)
display_dash_board(Report_card)

a: [('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
b: [('student3', 12), ('student4', 14), ('student9', 22), ('student6', 43), ('student1', 45)]
c: [('student9', 22), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [237]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)



cosine_dist=[]
for i,j in S:          #iterating trhough S 
  num = (i*P[0])+(j*P[1])                   #seprating numerator according to formula   
  deno = math.sqrt(i**2+j**2) * math.sqrt(P[0]**2+P[1]**2)     #seprating denominator according to formula

  cosine_dist.append(math.acos(num/deno))              #using math.acos to find cosine inverse 

#print(cosine_dist)
x= list(zip(S,cosine_dist))
x.sort(key=lambda e: e[1])                #sorting the S,cosine_dist     in increasing order
x=x[:5]                                   #slicing through x for 5 closest point
for i,j in x:
  print(i)                               #printing closest point


   





(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [238]:
import math


# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
    
# you can free to change all these codes/structure


def seprated_point(Red,Blue,line): 
    
    for i,j in enumerate(Red):              
      ele_1 = j[0]                          #assigning value from list of tupels                             
      ele_2 = j[1]
      m = eval(line.replace('x' , '*%s' % j[0]).replace('y', '*%s' % j[1]))      #using eval( )function to replace value in equation
      
      
    
    
    for o,p in enumerate(Blue):
        ele_3 = p[0]
        ele_4 = p[1]
        n= eval(line.replace('x' , '*%s' % ele_3).replace('y', '*%s' % ele_4))
        

    if m >0 and  n<0:
      print('YES')                     
      if m<0 and n>0 :
         print('YES')
    else:
      print('NO')   
    


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for k in Lines:
  answer = seprated_point(Red,Blue,k) 
                            
  

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [239]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

def replace_value(s):
    number_of_digit_in_string = 0
    split = s.split(',')
    count = 0
    middle_index = 0
    
    #left_values
    for i in range(len(split)):
        if split[i] == '_':
            count = count + 1  #counting number of blanks for left
        else:
            for j in range(i + 1):
                split[j] = str((float(split[i]) / (count + 1)))               #splitting the values with eaqual number of empty index
              
            middle_index = i
            middle_value = float(split[i])                                   #storing value for further addition
            break
    
    if middle_index+1 >= len(split):
      return split
    

    #middle_values
    divide = 1                                                       #creating divide variable and flag variable
    flag = 0
    for k in range(middle_index + 1, len(split)):                     #looping through middle part of string           
        if split[k] != '_':
            divide = (k + 1 - middle_index)                            #counting number of index to divide equally
            flag = k                                      #storing flag for flag value which is going to used in additon with left value
            break
    flag_value = float(split[flag])
    for m in range(middle_index, flag + 1):
        split[m] = str((middle_value+flag_value) / divide)          #assigning equally the divided value til flag =1 index

    # end value
    end_value = float(split[flag])             
    for n in range(flag, len(split)):
        split[n] = str(end_value / (len(split) - flag))                  #splitting  value equally over remaining index

    return split                  

s ="_,_,30,_,_,_,50,_,_"

replace_value(s)

['10.0', '10.0', '12.0', '12.0', '12.0', '12.0', '4.0', '4.0', '4.0']

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [240]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(F, S):
    # your code
    No_F_in_List = 0
    No_S_in_list = 0
    for i in range(len(A)):
        if(A[i][1] == S):
            No_S_in_list = No_S_in_list + 1                     #counting number of s in list
            if(A[i][0] == F):
                No_F_in_List = No_F_in_List + 1                 #no_f present in when given s 
    print('P(F = {} | S == {}) = {}/{}'.format(F, S, str(No_F_in_List), str(No_S_in_list)))
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

for f in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for s in ['S1', 'S2', 'S3']:
        compute_conditional_probabilites(f,s)

P(F = F1 | S == S1) = 1/4
P(F = F1 | S == S2) = 1/3
P(F = F1 | S == S3) = 0/3
P(F = F2 | S == S1) = 1/4
P(F = F2 | S == S2) = 1/3
P(F = F2 | S == S3) = 1/3
P(F = F3 | S == S1) = 0/4
P(F = F3 | S == S2) = 1/3
P(F = F3 | S == S3) = 1/3
P(F = F4 | S == S1) = 1/4
P(F = F4 | S == S2) = 0/3
P(F = F4 | S == S3) = 1/3
P(F = F5 | S == S1) = 1/4
P(F = F5 | S == S2) = 0/3
P(F = F5 | S == S3) = 0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [241]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    s1_words = set(S1.split())
    s2_words = set(S2.split())
    a = len(s1_words & s2_words)
    
    b = s1_words - s2_words
    c = s2_words - s1_words
    print('a:',a)
    print('b:',b)
    print('c:',c)

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)
#print(#the above values)

a: 7
b: {'first', '5', 'F'}
c: {'3', 'second', 'S'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [242]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
from math import log

# you can free to change all these codes/structure
def compute_log_loss(A):
    loss= 0
    for i in A:
      loss += i[0]* log(i[1],10) + (1-i[0])*log(1-i[1],10)          #calculating loss
      log_loss= -1 * (loss/len(A))                                  
    return log_loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
